version: '3.8'

services:
  backend:
    build: .
    container_name: harmonyai-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - .:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: harmonyai-frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    restart: unless-stopped
